### ISSUE TITLE
Right side page bit smaller 

### ISSUE THREAD

**Issue by arindammitra06** [doradsoft/flutter_flip_book#1]
Hi,

Thanks for the awesome library. I have a couple of questions. I see the right side of the page is a bit smaller than the left page. Can this be controlled to keep both pages same?

Also is there a way to rotate the screen to landscape and flip like a photo album?

I am trying to achieve the same using photos instead of text.

**Comment by doradsoft** [comment]
Closing as OP didn't contact me.
