### ISSUE TITLE
How to use onPageChanged()

### ISSUE THREAD

**Issue by arindammitra06** [doradsoft/flutter_flip_book#2]
I am trying to override an action onPageChanged() but I am unable ti use it. Can you please suggest how to use it? Thanks in advance. And thanks for the awesome package.

`FlipBook.builder(
                 controller: flipBookControllerEN,
                 pageBuilder: enPageBuilder,
                 padding: const EdgeInsets.symmetric(vertical: 0),
                 leafAspectRatio: leaf,
                 totalPages: widget.albumImages!.length,
                 albumImages : widget.albumImages,
                 addAutomaticKeepAlives: true,
                 onPageChanged: (index) {
                   pageChanged(index);
                 },
             )`

Whereas, 

pageChanged(int pageNumber) {
    if(pageNumber==0){
        setState(() {
          showTitleMessage = true;
          showEndMessage = false;
        });
    }else if(pageNumber==widget.albumImages!.length-1){
      showTitleMessage = false;
      showEndMessage = true;
    }else{
      showTitleMessage = false;
      showEndMessage = false;
    }
  }

**Comment by doradsoft** [comment]
As I'm very busy, and ping-ponging here will probably take a lot of time.
Please feel free to schedule a free session with me.
doradsoft@gmail.com
https://www.linkedin.com/in/dorad-levinshtein
I'll figure out what is missing and will try to upgrade the library to support it.

**Comment by doradsoft** [comment]
Closing as OP didn't contact me.

**Comment by doradsoft** [comment]
Closing as OP didn't contact me.

**Comment by arindammitra06** [comment]
Hi, Thanks for closing this. I am using this library in one of my projects to use it as a photo album, though I didn't pull it, but downloaded and modified it as per my requirement. It would be great if you could maintain this library and add features like page curls animation. 

This is the best library which actually works flawlessly on all environments- android, ios and web.  !!! Thanks again
